# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CommentsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os, sys

from PyQt5 import QtCore, QtGui, QtWidgets


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))

from helpers.Words import Words


class Ui_InsertComentWindow(object):
    def call_main_window(self) -> None:
        from .MainWindow import Ui_CommentsReviewer

        self.view_wnd = QtWidgets.QMainWindow()
        self.ui = Ui_CommentsReviewer()
        self.ui.setupUi(self.view_wnd)
        self.view_wnd.show()

    def clear_input_comment(self):
        self.input_comment.clear()

    def setupUi(self, InsertComentWindow):
        InsertComentWindow.setObjectName("InsertComentWindow")
        InsertComentWindow.resize(535, 457)
        InsertComentWindow.setMinimumSize(QtCore.QSize(520, 525))
        InsertComentWindow.setMaximumSize(QtCore.QSize(520, 525))
        self.centralwidget = QtWidgets.QWidget(InsertComentWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(120, 120, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_text.setFont(font)
        self.label_text.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_text.setObjectName("label_text")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(290, 260, 181, 41))
        self.submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit.setObjectName("submit")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(60, 260, 181, 41))
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setObjectName("back")
        self.back.clicked.connect(self.call_main_window)
        self.back.clicked.connect(InsertComentWindow.close)
        self.back.clicked.connect(self.clear_input_comment)
        self.input_comment = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.input_comment.setGeometry(QtCore.QRect(70, 180, 391, 61))
        self.input_comment.setObjectName("input_comment")
        self.submit.clicked.connect(lambda: Words(self.input_comment.toPlainText()).classify_word())
        self.submit.clicked.connect(lambda: self.clear_input_comment)
        InsertComentWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(InsertComentWindow)
        self.statusbar.setObjectName("statusbar")
        InsertComentWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InsertComentWindow)
        QtCore.QMetaObject.connectSlotsByName(InsertComentWindow)

    def retranslateUi(self, InsertComentWindow):
        _translate = QtCore.QCoreApplication.translate
        InsertComentWindow.setWindowTitle(_translate("InsertComentWindow", "Comments"))
        self.label_text.setText(
            _translate("InsertComentWindow", "Deixe seu Comentário")
        )
        self.submit.setText(_translate("InsertComentWindow", "CONCLUIR"))
        self.back.setText(_translate("InsertComentWindow", "VOLTAR"))
