# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from .CommentsWindow import Ui_InsertComentWindow


class Ui_CommentsReviewer(object):
    def call_window(self) -> None:
        self.view_wnd = QtWidgets.QMainWindow()
        self.ui = Ui_InsertComentWindow()
        self.ui.setupUi(self.view_wnd)
        self.view_wnd.show()

    def setupUi(self, CommentsReviewer):
        CommentsReviewer.setObjectName("CommentsReviewer")
        CommentsReviewer.resize(520, 525)
        CommentsReviewer.setMinimumSize(QtCore.QSize(520, 525))
        CommentsReviewer.setMaximumSize(QtCore.QSize(520, 525))
        self.centralwidget = QtWidgets.QWidget(CommentsReviewer)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 340, 281, 61))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.call_window)
        self.pushButton_2.clicked.connect(CommentsReviewer.close)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 120, 371, 111))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        CommentsReviewer.setCentralWidget(self.centralwidget)

        self.retranslateUi(CommentsReviewer)
        QtCore.QMetaObject.connectSlotsByName(CommentsReviewer)

    def retranslateUi(self, CommentsReviewer):
        _translate = QtCore.QCoreApplication.translate
        CommentsReviewer.setWindowTitle(
            _translate("CommentsReviewer", "CommentsReviewer")
        )
        self.pushButton_2.setText(_translate("CommentsReviewer", "AVALIAR"))
        self.label.setText(_translate("CommentsReviewer", "Comments Reviewer"))
